### ISSUE TITLE
`apacite` conflict using Overleaf

### ISSUE THREAD

**Issue by nikmart** [madpickle/HCIJ_LaTeX_Template#1]
Hi there! Thanks for creating this LaTeX template. When I uploaded this to Overleaf and switched to the main article, I received the following compiler error:

```shell
Package biblatex Error: Incompatible package 'apacite'.
See the biblatex package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.155 \blx@packageincompatibility
                                 
The 'apacite' package and biblatex are incompatible.
```

I commented out `\RequirePackage{apacite}` in `hcij.cls` and could compile successfully. But, I wanted to make see if this would be the correct solution.

Thanks again for creating this!

Nik

**Comment by madpickle** [comment]
Well spotted. Overleaf has clearly been updated since this template was written. I've now updated the code to address these (and other) issues. Everything compiles for me now with no errors nor warnings in Overleaf. Please let me know if that is also the case for you (and if not what is broken). Thanks.

**Comment by nikmart** [comment]
For some reason, \LaTeX\ does not render in the References. Using a clean Overleaf upload of the project files I get:

```shell
<argument> The \latex 
                      \ companion
l.51 ...\LaTeX\ Companion} {The \latex\ companion}
                                                  .
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

)
Package atveryend Info: Empty hook `BeforeClearDocument' on input line 95.
[4
```

in line 51 of `output.bbl`

`\APACrefbtitle {The \LaTeX\ Companion} {The \latex\ companion}.`

Have no idea why the `\LaTeX\ ` command would not work. Tried to fix but have not figured it out. It seems that the second part of the bbl line is becoming `\latex` all lowercase.... Honestly, I wouldn't notice this if I had just swapped my `.bib` file like I usually do.

Also, `RequirePackage{apacite}` is on line `31` and `37` of `hcij.cls`

**Comment by nikmart** [comment]
Ok, now fixed it by putting `\LaTeX\` into double curly braces `{{\LaTeX}}`. Seems this might be a property of BibTeX lowercasing words.

Full citation:

```tex
@book{latexcompanion,
    author    = "Michel Goossens and Frank Mittelbach and Alexander Samarin",
    title     = "The {{\LaTeX}} Companion",
    year      = "1993",
    publisher = "Addison-Wesley",
    address   = "Reading, Massachusetts"
}
```

**Comment by madpickle** [comment]
Yep! Sorry, I forgot to commit that fix. Now it should be there. Thanks. All OK now?

**Comment by nikmart** [comment]
Yup, all good now. No errors with a fresh version. Thanks!
